name: Deploy to Web

env:
  FORCE_COLOR: 1
  NODE_VERSION: lts/*

concurrency:
  group: deploy-to-neocities
  cancel-in-progress: true

on:
  push:
    branches:
      - master
      # make sure your branch name matches! (ie. main, master, etc)

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repository code
        uses: actions/checkout@v4
        
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
        # this will use the latest LTS version of Node.js
        # if you need a specific version, replace ${{ env.NODE_VERSION }} with that version number
        
      - name: Get npm cache directory
        id: npm-cache-dir
        run: echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT
        
      - name: Cache npm dependencies
        uses: actions/cache@v4
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
        # caches dependencies and other commonly re-used files
        # so they do not need to be re-installed on each run
        
      - name: Install dependencies and build site
        run: |
          npm ci
          npm run build

      - name: SFTP uploader
        uses: wangyucode/sftp-upload-action@v2.0.4
        with:
          host: "lastsunrise.art"
          username: "lastsunrise"
          password: ${{ secrets.SFTP_PASSWORD }}
          localDir: "dist"
          remoteDir: "/home/lastsunrise/htdocs/lastsunrise.art/"

      - name: Add Redirect to HTML Files
        run: |
          for file in $(find dist -name '*.html'); do
            url_path=$(echo $file | sed 's/dist\///' | sed 's/\index.html$//')
            sed -i 's|<head>|<head><meta http-equiv="refresh" content="0; URL=https://lastsunrise.art/'"$url_path"'">|' "$file"
          done
        
      # THIS & THE PREVIOUS REST OF THIS SCRIPT ARE FROM https://github.com/professorsugoi/Deploy-Astro-Neocities/tree/master
      - name: Deploy to Neocities
        uses: bcomnes/deploy-to-neocities@master
        with:
          api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
          cleanup: true
          dist_dir: dist
        # if dist_dir is within a subfolder, update the filepath to reflect that

    # FROM https://github.com/deploy2nekoweb/deploy2nekoweb
      - name: deploy2nekoweb
        uses: deploy2nekoweb/deploy2nekoweb@v4
        with:
          nekoweb-api-key: ${{ secrets.NEKOWEB_API_KEY }}
          nekoweb-cookie: ${{ secrets.NEKOWEB_COOKIE }}
          nekoweb-folder: 'site'
          directory: 'dist'